# Your Solution
version: '3.8'

services:
  book_catalog:
    image: sit722project.azurecr.io/book_catalog:latest
    container_name: book_catalog
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password123*@db:5432/postgres
    depends_on:
      - db

  inventory_management:
    image: sit722project.azurecr.io/inventory_management:latest
    container_name: inventory_management
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password123*@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123*
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: